trigger:
  branches:
    include:
    - master

pr:
  branches:
    include:
    - master
    - feature/*

jobs:
- job: WebApp
  pool:
    vmImage: vs2017-win2016 # https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops
  steps:
  - template: templates/azure-pipelines-steps.aspnetcore.yml
    parameters:
     gitVersionVersion: '5.0.0-beta2-18' # release latest version here https://www.nuget.org/packages/GitVersion.CommandLine.DotNetCore
     nugetVersion: '4.9.4' # see recommended version here https://www.nuget.org/downloads
     buildConfiguration: 'Release'
     deployPackage: true
     deployFiles: true
     outputDirectory: $(Build.ArtifactStagingDirectory)
