resources:
- repo: self

trigger:
  batch: false # batch changes if true, start a new build for every push if false
  branches:
    include:
    - master

jobs:
- job: WebApp
  pool:
    vmImage: vs2017-win2016
  steps:
  - template: templates/azure-pipelines-steps.aspnetcore.yml
    parameters:
     gitVersionVersion: '4.0.0-beta0012' # release latest version here https://www.nuget.org/packages/GitVersion
     nugetVersion: '4.9.2' # see recommended version here https://www.nuget.org/downloads
     buildConfiguration: 'Release'
     deployPackage: true
     deployFiles: true