parameters:
  gitVersionVersion: ''
  nugetVersion: ''

steps:
- task: NuGetToolInstaller@0
  displayName: NuGet use ${{ parameters.nugetVersion }}
  inputs:
    versionSpec: ${{ parameters.nugetVersion }}

- task: NuGetCommand@2
  displayName: NuGet Install GitVersion
  inputs:
    command: custom
    arguments: install GitVersion.CommandLine.DotNetCore -Version ${{ parameters.gitVersionVersion }} -OutputDirectory $(Build.BinariesDirectory)

- powershell: dotnet $(Build.BinariesDirectory)\GitVersion.CommandLine.DotNetCore.${{ parameters.gitVersionVersion }}\tools\GitVersion.dll $(Build.SourcesDirectory) /output buildserver /nofetch
  displayName: GitVersion Execute

- powershell:   |
    $CI_Version = "$env:GITVERSION_LEGACYSEMVER"
    Write-Host ("##vso[task.setvariable variable=CI_Version;]$CI_Version")
    Write-Host "Build ID: $(Build.BuildId)"
    Write-Host "Build BuildNumber: $(Build.BuildNumber)"
  displayName: "Build Versions"
