trigger:
  branches:
    include:
    - master

pr:
  branches:
    include:
    - master
    - feature/*

jobs:
- job: WebApp
  steps:
  - template: build/azure-pipelines-steps.init.yml
    parameters:
      toolPath: '$(Build.BinariesDirectory)'
      dotnetInstallConfigFile: 'NuGet.config' # workaround for a bug in dotnet cli https://github.com/dotnet/cli/issues/9586#issuecomment-484585146
      gitVersionVersion: '5.0.0-beta5.9' # release latest version here https://www.nuget.org/packages/GitVersion.CommandLine.DotNetCore
      nugetVersion: '5.0.2' # see recommended version here https://www.nuget.org/downloads
  - template: build/azure-pipelines-steps.angular.yml
    parameters:
      path: src