resources:
- repo: self

trigger:
  branches:
    include:
    - master

jobs:
- job: NuGet
  pool:
    vmImage: vs2017-win2016
  steps:
  - template: templates/azure-pipelines-steps.dotnet-nuget.yml
    parameters:
      gitVersionVersion: '4.0.0-beta0012' # release latest version here https://www.nuget.org/packages/GitVersion
      nugetVersion: '4.9.2' # see recommended version here https://www.nuget.org/downloads
      buildConfiguration: 'Release'
      packagesToPack: src\**\*.csproj
      # Publishes all created NuGet packages to your artifacts