trigger:
  branches:
    include:
    - master

pr:
  branches:
    include:
    - master
    - feature/*

variables:
  PackagesToPack: 'src\**\*.csproj'
  BuildConfig: 'Release'
  GitVersionVersion: '5.1.1' # release latest version here https://www.nuget.org/packages/GitVersion.Tool
  NuGetVersion: '5.3.1' # see recommended version here https://www.nuget.org/downloads

jobs:
- job: NuGet
  pool:
    vmImage: windows-2019 # https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops
  steps:
  - template: build/azure-pipelines-steps.dotnet-nuget.yml
    parameters:
      gitVersionVersion: $(Build.GitVersionVersion)
      nugetVersion: $(Build.NuGetVersion)
      buildConfiguration: $(Build.BuildConfig)
      packagesToPack: $(Build.PackagesToPack)
      # Publishes all created NuGet packages to your artifacts
