trigger:
  branches:
    include:
    - master

pr:
  branches:
    include:
    - master
    - feature/*

variables:
  Docker.Registry: mydockerregistry # TODO: Replace with your Docker Username
  Docker.Repository: mydockerrepository # TODO: Replace with your Docker ImageName
  Docker.ImageName: mydockerimagename # TODO: Replace with your Docker RepositoryName
  SourcePath: 'src'
  BuildConfig: 'Release'
  NuGetConfigPath: 'NuGet.config' # workaround for a bug in dotnet cli https://github.com/dotnet/cli/issues/9586#issuecomment-484585146
  GitVersionVersion: '5.1.1' # release latest version here https://www.nuget.org/packages/GitVersion.Tool
  NuGetVersion: '5.3.1' # see recommended version here https://www.nuget.org/downloads

jobs:
- job: WebApp
  pool:
    vmImage: vs2017-win2016 # https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops
  steps:
  - template: build/azure-pipelines-steps.aspnetcore.yml  # see AspNetCore/azure-pipelines-steps.aspnetcore.yml
    parameters:
     gitVersionVersion: $(Build.GitVersionVersion)
     nugetVersion: $(Build.NuGetVersion)
     buildConfiguration: $(Build.BuildConfig)
     deployPackage: false
     deployFiles: true # files only here
     outputDirectory: $(Build.ArtifactStagingDirectory)/app

- job: DockerOnLinux
  dependsOn: WebApp
  pool:
    vmImage: ubuntu-16.04 # https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops
  steps:
  - template: build/azure-pipelines-steps.docker-azurecr-from-files-template.yml  # Template reference
    parameters:
     dockerRegistry: $(Docker.Registry)
     dockerRepository: $(Docker.Repository)
     dockerImageName: $(Docker.ImageName)
     dockerImageTag: $(Build.BuildNumber)
     dockerFile: src/MyApp/Dockerfile.Linux
     dockerContents: '$(System.ArtifactsDirectory)/drop/files/MyAspNetCoreApp' # artifacts from AspNetCore/azure-pipelines-steps.aspnetcore.yml
     artifactsTargetFolder: $(System.DefaultWorkingDirectory)/_artifacts/dockercontents
     dockerAzureSubscriptionName: 'Your Subscription Name'
     dockerAzureCRSubscription: 'YourAzureContainerRegistrySubscription'
     # TODO: Replace MyAspNetCoreApp with your AppName

- job: DockerOnWindows
  dependsOn: WebApp
  pool:
    vmImage: win1803
  steps:
  - template: build/azure-pipelines-steps.docker-azurecr-from-files-template.yml  # Template reference
    parameters:
     dockerRegistry: $(Docker.Registry)
     dockerRepository: $(Docker.Repository)
     dockerImageName: $(Docker.ImageName)
     dockerImageTag: $(Build.BuildNumber)
     dockerFile: src/MyApp/Dockerfile.windowsservercore-1803
     dockerContents: '$(System.ArtifactsDirectory)/drop/files/MyAspNetCoreApp' # artifacts from AspNetCore/azure-pipelines-steps.aspnetcore.yml
     artifactsTargetFolder: $(System.DefaultWorkingDirectory)/_artifacts/dockercontents
     dockerAzureSubscriptionName: 'Your Subscription Name'
     dockerAzureCRSubscription: 'YourAzureContainerRegistrySubscription'
     # TODO: Replace MyAspNetCoreApp with your AppName
