trigger:
  branches:
    include:
    - master

pr:
  branches:
    include:
    - master
    - feature/*

variables:
  Docker.Registry: mydockerregistry # TODO: Replace with your Docker Username
  Docker.Repository: mydockerrepository # TODO: Replace with your Docker ImageName
  Docker.ImageName: mydockerimagename # TODO: Replace with your Docker RepositoryName

jobs:
- job: WebApp
  pool:
    vmImage: vs2017-win2016
  steps:
  - template: templates/azure-pipelines-steps.aspnetcore.yml  # see AspNetCore/azure-pipelines-steps.aspnetcore.yml
    parameters:
     gitVersionVersion: '5.0.0-beta2-18' # release latest version here https://www.nuget.org/packages/GitVersion.CommandLine.DotNetCore
     nugetVersion: '4.9.2' # see recommended version here https://www.nuget.org/downloads
     buildConfiguration: 'Release'
     deployPackage: false
     deployFiles: true # files only here
     outputDirectory: $(Build.ArtifactStagingDirectory)/app

- job: DockerOnLinux
  dependsOn: WebApp
  pool:
    vmImage: ubuntu-16.04
  steps:
  - template: templates/azure-pipelines-steps.docker-azurecr-from-files-template.yml  # Template reference
    parameters:
     dockerRegistry: $(Docker.Registry)
     dockerRepository: $(Docker.Repository)
     dockerImageName: $(Docker.ImageName)
     dockerImageTag: $(Build.BuildNumber)
     dockerFile: src/MyApp/Dockerfile.Linux
     dockerContents: '$(System.ArtifactsDirectory)/drop/files/MyAspNetCoreApp' # artifacts from AspNetCore/azure-pipelines-steps.aspnetcore.yml
     artifactsTargetFolder: $(System.DefaultWorkingDirectory)/_artifacts/dockercontents
     dockerAzureSubscriptionName: 'Your Subscription Name'
     dockerAzureCRSubscription: 'YourAzureContainerRegistrySubscription'
     # TODO: Replace MyAspNetCoreApp with your AppName

- job: DockerOnWindows
  dependsOn: WebApp
  pool:
    vmImage: win1803
  steps:
  - template: templates/azure-pipelines-steps.docker-azurecr-from-files-template.yml  # Template reference
    parameters:
     dockerRegistry: $(Docker.Registry)
     dockerRepository: $(Docker.Repository)
     dockerImageName: $(Docker.ImageName)
     dockerImageTag: $(Build.BuildNumber)
     dockerFile: src/MyApp/Dockerfile.windowsservercore-1803
     dockerContents: '$(System.ArtifactsDirectory)/drop/files/MyAspNetCoreApp' # artifacts from AspNetCore/azure-pipelines-steps.aspnetcore.yml
     artifactsTargetFolder: $(System.DefaultWorkingDirectory)/_artifacts/dockercontents
     dockerAzureSubscriptionName: 'Your Subscription Name'
     dockerAzureCRSubscription: 'YourAzureContainerRegistrySubscription'
     # TODO: Replace MyAspNetCoreApp with your AppName
